2018-11-25 15:57:38,211 ERROR: Exception on /edit_profile [GET] [in /Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/app/main/routes.py", line 106, in edit_profile
    form=form)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/evh111/Desktop/programz/petblog/app/templates/edit_profile.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/evh111/Desktop/programz/petblog/app/templates/base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/evh111/Desktop/programz/petblog/app/templates/base.html", line 66, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/evh111/Desktop/programz/petblog/app/templates/edit_profile.html", line 6, in block "app_content"
    <td width="256px"><img src="{{ user.avatar(256) }}"></td>
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2018-11-25 15:59:49,001 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 15:59:55,407 ERROR: Exception on /edit_profile [GET] [in /Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
TypeError: edit_profile() missing 1 required positional argument: 'username'
2018-11-25 16:00:58,739 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 16:06:43,089 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 16:06:48,703 ERROR: Exception on /edit_profile [GET] [in /Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/app/main/routes.py", line 106, in edit_profile
    form=form)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/evh111/Desktop/programz/petblog/app/templates/edit_profile.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/evh111/Desktop/programz/petblog/app/templates/base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/evh111/Desktop/programz/petblog/app/templates/base.html", line 66, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/evh111/Desktop/programz/petblog/app/templates/edit_profile.html", line 8, in block "app_content"
    <a href="{{ url_for('main.user', username=post.author.username) }}">
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2018-11-25 16:07:18,084 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 16:09:10,051 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 16:09:42,859 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
