2018-11-23 19:01:42,424 ERROR: Exception on /auth/login [GET] [in /Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/evh111/Desktop/programz/petblog/app/auth/routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/evh111/Desktop/programz/petblog/app/templates/auth/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/evh111/Desktop/programz/petblog/app/templates/base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/evh111/Desktop/programz/petblog/app/templates/base.html", line 66, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/evh111/Desktop/programz/petblog/app/templates/auth/login.html", line 12, in block "app_content"
    <p>{{ _('New Pet?') }} <a href="{{ url_for('auth.get_started') }}">{{ _('Get Started!') }}</a></p>
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'auth.get_started'. Did you mean 'auth.reset_password' instead?
2018-11-23 19:02:43,255 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 19:13:32,018 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 19:13:45,145 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 19:22:10,216 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 19:26:50,439 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 19:28:32,057 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 19:31:38,364 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 19:35:54,743 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 19:38:49,881 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 19:38:53,088 ERROR: Exception on /edit_profile [GET] [in /Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/app/main/routes.py", line 89, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/app/main/forms.py", line 23, in __init__
    super(EditProfileForm, self).__init__(*arg, **kwargs)
NameError: name 'arg' is not defined
2018-11-23 19:39:11,489 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 19:40:31,753 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 19:41:04,147 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 20:08:55,262 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 20:58:06,688 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-23 21:04:32,443 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 13:53:18,301 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 13:53:25,079 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 13:58:18,506 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 14:03:17,227 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
